apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: dev
  name: dev-command-database-deployment
  labels:
    app: dev
    tier: command-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dev
        tier: database
    spec:
      containers:
      - name: database
        image: logcorneredusync.azurecr.io/logcorner-edusync-speech-presentation-data
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "PassW0rd"
        - name: ACCEPT_EULA
          value: "Y"
      imagePullSecrets:
        - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: dev-command-database-service
  labels:
    app: dev
    tier: command-db
spec:
  ports:
  - name: sqlserver
    port: 1433
    targetPort: 1433
  selector:
    app: dev
    tier: database
  type: LoadBalancer
