apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dev-command-api-deployment
  namespace: __namespace__
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: __namespace__
        tier: command-api
    spec:
      containers:
      - name: command
        image: __ContainerRegistry__/logcorner-edusync-speech-presentation
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "__AspNetCoreEnvironment__"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
        - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  name: dev-command-api-service
  namespace: __namespace__
  labels:
    app: __namespace__
    tier: command-api
spec:
  selector:
    app: __namespace__
    tier: command-api
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30082
  type: LoadBalancer

