version: '3.4'

services:
  logcorner.edusync.speech.domain.unittest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/tests-results-domain.xml
  logcorner.edusync.speech.application.unittest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/test-results-application.xml
   
  logcorner.edusync.speech.infrastructure.unittest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/test-results-infrastructure.xml
   
    
