version: '3.4'

services:
  logcorner.edusync.speech.domain.unittest:
    environment:
      - ASPNETCORE_ENVIRONMENT=UnitTest
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/domain-tests/tests-results-domain.xml
  logcorner.edusync.speech.application.unittest:
    environment:
      - ASPNETCORE_ENVIRONMENT=UnitTest
    
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/application-tests/tests-results-application.xml
   
  logcorner.edusync.speech.infrastructure.unittest:
    environment:
      - ASPNETCORE_ENVIRONMENT=UnitTest
    
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/infrastructure-tests/tests-results-infrastructure.xml

  logcorner.edusync.speech.presentation.unittest:
    environment:
      - ASPNETCORE_ENVIRONMENT=UnitTest
    
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/presentation-tests/tests-results-presentation.xml
   
    
